In [1]:
import pandas as pd

print("Pandas funcionando")

Pandas funcionando

In [2]:
df1 = pd.read_csv("index_1.csv")
df2 = pd.read_csv("index_2.csv")

In [3]:
df1.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [4]:
df2.head()

         date             datetime cash_type  money            coffee_name
0  2025-02-08  2025-02-08 14:26:04      cash   15.0                    Tea
1  2025-02-08  2025-02-08 14:28:26      cash   15.0                    Tea
2  2025-02-08  2025-02-08 14:33:04      card   20.0               Espresso
3  2025-02-08  2025-02-08 15:51:04      card   30.0  Chocolate with coffee
4  2025-02-08  2025-02-08 16:35:01      cash   27.0    Chocolate with milk

In [5]:
df1.shape

(3636, 6)

In [6]:
df2.shape

(262, 5)

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   str
 1   datetime     3636 non-null   str
 2   cash_type    3636 non-null   str
 3   card         3547 non-null   str
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   str
dtypes: float64(1), str(5)
memory usage: 170.6 KB

In [8]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         262 non-null    str
 1   datetime     262 non-null    str
 2   cash_type    262 non-null    str
 3   money        262 non-null    float64
 4   coffee_name  262 non-null    str
dtypes: float64(1), str(4)
memory usage: 10.4 KB

In [9]:
df1.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [10]:
df2.isnull().sum()

date           0
datetime       0
cash_type      0
money          0
coffee_name    0
dtype: int64

In [11]:
df1["cash_type"].value_counts()

cash_type
card    3547
cash      89
Name: count, dtype: int64

In [12]:
df2["cash_type"].value_counts()

cash_type
card    182
cash     80
Name: count, dtype: int64

In [13]:
df1[df1["card"].isnull()]["cash_type"].value_counts()

cash_type
cash    89
Name: count, dtype: int64

In [15]:
df2["card"] = pd.NA

In [16]:
df2 = df2[df1.columns]

In [17]:
df = pd.concat([df1, df2], ignore_index=True)

In [18]:
df.shape

(3898, 6)

In [19]:
df.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [20]:
df.tail()

,date,datetime,cash_type,card,money,coffee_name
3893,2025-03-23,2025-03-23 14:55:46,cash,<NA>,30.0,Cappuccino
3894,2025-03-23,2025-03-23 15:15:36,card,<NA>,25.0,Irish whiskey
3895,2025-03-23,2025-03-23 17:59:25,card,<NA>,28.0,Super chocolate
3896,2025-03-23,2025-03-23 18:01:33,card,<NA>,28.0,Vanilla with Irish whiskey
3897,2025-03-23,2025-03-23 21:23:11,card,<NA>,29.0,Coffee with Irish whiskey

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3898 entries, 0 to 3897
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3898 non-null   str
 1   datetime     3898 non-null   str
 2   cash_type    3898 non-null   str
 3   card         3547 non-null   object
 4   money        3898 non-null   float64
 5   coffee_name  3898 non-null   str
dtypes: float64(1), object(1), str(4)
memory usage: 182.8+ KB

In [22]:
df.isnull().sum()

date             0
datetime         0
cash_type        0
card           351
money            0
coffee_name      0
dtype: int64

In [23]:
df["date"] = pd.to_datetime(df["date"])
df["datetime"] = pd.to_datetime(df["datetime"])

ValueError: time data "2025-02-08 14:26:04" doesn't match format "%Y-%m-%d %H:%M:%S.%f". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [24]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["datetime"] = pd.to_datetime(df["datetime"], format="mixed", errors="coerce")

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3898 entries, 0 to 3897
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3898 non-null   datetime64[us]
 1   datetime     3898 non-null   datetime64[us]
 2   cash_type    3898 non-null   str
 3   card         3547 non-null   object
 4   money        3898 non-null   float64
 5   coffee_name  3898 non-null   str
dtypes: datetime64[us](2), float64(1), object(1), str(2)
memory usage: 182.8+ KB

In [26]:
df[["date", "datetime"]].isnull().sum()

date        0
datetime    0
dtype: int64

In [27]:
df["ano"] = df["date"].dt.year
df["mes"] = df["date"].dt.month
df["dia"] = df["date"].dt.day
df["hora"] = df["datetime"].dt.hour
df["dia_semana"] = df["date"].dt.day_name()

In [28]:
df.head()

,date,datetime,cash_type,card,money,coffee_name,ano,mes,dia,hora,dia_semana
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,2024,3,1,10,Friday
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,3,1,12,Friday
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,3,1,12,Friday
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,2024,3,1,13,Friday
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,2024,3,1,13,Friday

In [29]:
df["coffee_name"].value_counts()

coffee_name
Americano with Milk           824
Latte                         806
Americano                     593
Cappuccino                    517
Cortado                       292
Hot Chocolate                 282
Cocoa                         243
Espresso                      152
Americano with milk            44
Irish whiskey                  21
Tea                            16
Coffee with Irish whiskey      16
Irish whiskey with milk        15
Chocolate with milk            12
Double Irish whiskey           12
Caramel with Irish whiskey      8
Super chocolate                 6
Chocolate with coffee           5
Mochaccino                      5
Irish with chocolate            5
Caramel with chocolate          4
Vanilla with Irish whiskey      3
Caramel with milk               3
Double espresso with milk       2
Double vanilla                  2
Caramel coffee                  2
Double espresso                 1
Chocolate                       1
Coffee with chocolate           1
Vanilla coffee                  1
Double ristretto                1
Hot milkshake                   1
Double chocolate                1
Caramel                         1
Name: count, dtype: int64

In [30]:
df["cash_type"].value_counts()

cash_type
card    3729
cash     169
Name: count, dtype: int64

In [31]:
df["dia_semana"].value_counts()

dia_semana
Tuesday      604
Monday       591
Friday       586
Wednesday    553
Thursday     540
Saturday     531
Sunday       493
Name: count, dtype: int64

In [32]:
df["hora"].value_counts().sort_index()

hora
6       5
7      99
8     246
9     258
10    363
11    316
12    271
13    241
14    245
15    267
16    307
17    267
18    247
19    253
20    177
21    210
22    123
23      3
Name: count, dtype: int64

In [33]:
df["coffee_name_clean"] = df["coffee_name"].str.strip().str.lower()
df["cash_type"] = df["cash_type"].str.strip().str.lower()

In [34]:
df.head()

,date,datetime,cash_type,card,money,coffee_name,ano,mes,dia,hora,dia_semana,coffee_name_clean
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,2024,3,1,10,Friday,latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,3,1,12,Friday,hot chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,2024,3,1,12,Friday,hot chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,2024,3,1,13,Friday,americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,2024,3,1,13,Friday,latte

In [35]:
df["coffee_name_clean"].value_counts()

coffee_name_clean
americano with milk           868
latte                         806
americano                     593
cappuccino                    517
cortado                       292
hot chocolate                 282
cocoa                         243
espresso                      152
irish whiskey                  21
tea                            16
coffee with irish whiskey      16
irish whiskey with milk        15
chocolate with milk            12
double irish whiskey           12
caramel with irish whiskey      8
super chocolate                 6
chocolate with coffee           5
mochaccino                      5
irish with chocolate            5
caramel with chocolate          4
vanilla with irish whiskey      3
caramel with milk               3
double espresso with milk       2
double vanilla                  2
caramel coffee                  2
double espresso                 1
chocolate                       1
coffee with chocolate           1
vanilla coffee                  1
double ristretto                1
hot milkshake                   1
double chocolate                1
caramel                         1
Name: count, dtype: int64

In [36]:
df["coffee_name_formatado"] = df["coffee_name_clean"].str.title()

In [37]:
df[["coffee_name", "coffee_name_clean", "coffee_name_formatado"]].head(10)

           coffee_name    coffee_name_clean coffee_name_formatado
0                Latte                latte                 Latte
1        Hot Chocolate        hot chocolate         Hot Chocolate
2        Hot Chocolate        hot chocolate         Hot Chocolate
3            Americano            americano             Americano
4                Latte                latte                 Latte
5  Americano with Milk  americano with milk   Americano With Milk
6        Hot Chocolate        hot chocolate         Hot Chocolate
7  Americano with Milk  americano with milk   Americano With Milk
8                Cocoa                cocoa                 Cocoa
9  Americano with Milk  americano with milk   Americano With Milk

In [38]:
resumo_cafe = df.groupby("coffee_name_formatado").agg(
    qtd_vendas=("coffee_name_formatado", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).sort_values(by="faturamento_total", ascending=False)

resumo_cafe

                            qtd_vendas  faturamento_total  ticket_medio
coffee_name_formatado
Latte                              806           28658.30     35.556203
Americano With Milk                868           26369.12     30.379171
Cappuccino                         517           18514.14     35.810716
Americano                          593           15437.26     26.032479
Hot Chocolate                      282           10172.46     36.072553
Cocoa                              243            8678.16     35.712593
Cortado                            292            7534.86     25.804315
Espresso                           152            3187.28     20.968947
Irish Whiskey                       21             525.00     25.000000
Coffee With Irish Whiskey           16             464.00     29.000000
Irish Whiskey With Milk             15             405.00     27.000000
Double Irish Whiskey                12             336.00     28.000000
Chocolate With Milk                 12             324.00     27.000000
Tea                                 16             240.00     15.000000
Caramel With Irish Whiskey           8             224.00     28.000000
Super Chocolate                      6             168.00     28.000000
Chocolate With Coffee                5             150.00     30.000000
Mochaccino                           5             150.00     30.000000
Irish With Chocolate                 5             135.00     27.000000
Caramel With Chocolate               4             112.00     28.000000
Vanilla With Irish Whiskey           3              84.00     28.000000
Caramel With Milk                    3              75.00     25.000000
Double Espresso With Milk            2              64.00     32.000000
Caramel Coffee                       2              56.00     28.000000
Double Vanilla                       2              47.00     23.500000
Hot Milkshake                        1              30.00     30.000000
Coffee With Chocolate                1              28.00     28.000000
Double Ristretto                     1              27.00     27.000000
Double Espresso                      1              27.00     27.000000
Vanilla Coffee                       1              27.00     27.000000
Chocolate                            1              25.00     25.000000
Double Chocolate                     1              25.00     25.000000
Caramel                              1              22.00     22.000000

In [39]:
resumo_cafe = resumo_cafe.reset_index()

resumo_cafe["faturamento_total"] = resumo_cafe["faturamento_total"].round(2)
resumo_cafe["ticket_medio"] = resumo_cafe["ticket_medio"].round(2)

resumo_cafe.head(10)

       coffee_name_formatado  qtd_vendas  faturamento_total  ticket_medio
0                      Latte         806           28658.30         35.56
1        Americano With Milk         868           26369.12         30.38
2                 Cappuccino         517           18514.14         35.81
3                  Americano         593           15437.26         26.03
4              Hot Chocolate         282           10172.46         36.07
5                      Cocoa         243            8678.16         35.71
6                    Cortado         292            7534.86         25.80
7                   Espresso         152            3187.28         20.97
8              Irish Whiskey          21             525.00         25.00
9  Coffee With Irish Whiskey          16             464.00         29.00

In [40]:
resumo_hora = df.groupby("hora").agg(
    qtd_vendas=("hora", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index().sort_values(by="hora")

resumo_hora["faturamento_total"] = resumo_hora["faturamento_total"].round(2)
resumo_hora["ticket_medio"] = resumo_hora["ticket_medio"].round(2)

resumo_hora

    hora  qtd_vendas  faturamento_total  ticket_medio
0      6           5             149.40         29.88
1      7          99            3161.02         31.93
2      8         246            7329.88         29.80
3      9         258            7697.28         29.83
4     10         363           11357.52         31.29
5     11         316            9411.10         29.78
6     12         271            8190.62         30.22
7     13         241            7448.76         30.91
8     14         245            7705.80         31.45
9     15         267            8380.02         31.39
10    16         307            9846.60         32.07
11    17         267            8537.00         31.97
12    18         247            7965.60         32.25
13    19         253            8461.96         33.45
14    20         177            5821.92         32.89
15    21         210            6835.94         32.55
16    22         123            3934.16         31.99
17    23           3              87.00         29.00

In [41]:
resumo_hora.sort_values(by="faturamento_total", ascending=False).head(10)

    hora  qtd_vendas  faturamento_total  ticket_medio
4     10         363           11357.52         31.29
10    16         307            9846.60         32.07
5     11         316            9411.10         29.78
11    17         267            8537.00         31.97
13    19         253            8461.96         33.45
9     15         267            8380.02         31.39
6     12         271            8190.62         30.22
12    18         247            7965.60         32.25
8     14         245            7705.80         31.45
3      9         258            7697.28         29.83

In [42]:
resumo_dia_semana = df.groupby("dia_semana").agg(
    qtd_vendas=("dia_semana", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index()

resumo_dia_semana["faturamento_total"] = resumo_dia_semana["faturamento_total"].round(2)
resumo_dia_semana["ticket_medio"] = resumo_dia_semana["ticket_medio"].round(2)

resumo_dia_semana.sort_values(by="faturamento_total", ascending=False)

  dia_semana  qtd_vendas  faturamento_total  ticket_medio
5    Tuesday         604           19148.38         31.70
1     Monday         591           18714.10         31.67
0     Friday         586           18357.66         31.33
6  Wednesday         553           17182.46         31.07
4   Thursday         540           17025.40         31.53
2   Saturday         531           16422.52         30.93
3     Sunday         493           15471.06         31.38

In [43]:
df["periodo_dia"] = pd.cut(
    df["hora"],
    bins=[5, 12, 15, 18, 24],
    labels=["Manhã", "Almoço/Início da tarde", "Tarde", "Noite"],
    right=False
)

In [44]:
resumo_periodo = df.groupby("periodo_dia").agg(
    qtd_vendas=("periodo_dia", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index()

resumo_periodo["faturamento_total"] = resumo_periodo["faturamento_total"].round(2)
resumo_periodo["ticket_medio"] = resumo_periodo["ticket_medio"].round(2)

resumo_periodo.sort_values(by="faturamento_total", ascending=False)

              periodo_dia  qtd_vendas  faturamento_total  ticket_medio
0                   Manhã        1287           39106.20         30.39
3                   Noite        1013           33106.58         32.68
2                   Tarde         841           26763.62         31.82
1  Almoço/Início da tarde         757           23345.18         30.84

In [45]:
resumo_periodo = df.groupby("periodo_dia").agg(
    qtd_vendas=("periodo_dia", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean"),
    horas_ativas=("hora", "nunique")
).reset_index()

resumo_periodo["faturamento_total"] = resumo_periodo["faturamento_total"].round(2)
resumo_periodo["ticket_medio"] = resumo_periodo["ticket_medio"].round(2)

resumo_periodo["vendas_media_por_hora"] = (
    resumo_periodo["qtd_vendas"] / resumo_periodo["horas_ativas"]
).round(2)

resumo_periodo["faturamento_medio_por_hora"] = (
    resumo_periodo["faturamento_total"] / resumo_periodo["horas_ativas"]
).round(2)

resumo_periodo.sort_values(by="faturamento_medio_por_hora", ascending=False)

,periodo_dia,qtd_vendas,faturamento_total,ticket_medio,horas_ativas,vendas_media_por_hora,faturamento_medio_por_hora
2,Tarde,841,26763.62,31.82,3,280.33,8921.21
1,Almoço/Início da tarde,757,23345.18,30.84,3,252.33,7781.73
0,Manhã,1287,39106.20,30.39,6,214.50,6517.70
3,Noite,1013,33106.58,32.68,6,168.83,5517.76

In [46]:
df["card_status"] = df["card"].copy()

df.loc[(df["cash_type"] == "cash") & (df["card_status"].isna()), "card_status"] = "Não se aplica"

df.loc[(df["cash_type"] == "card") & (df["card_status"].isna()), "card_status"] = "Não informado"

In [47]:
df["card_status"].isnull().sum()

np.int64(0)

In [48]:
df[["cash_type", "card", "card_status"]].tail(10)

     cash_type  card    card_status
3888      card  <NA>  Não informado
3889      card  <NA>  Não informado
3890      cash  <NA>  Não se aplica
3891      cash  <NA>  Não se aplica
3892      cash  <NA>  Não se aplica
3893      cash  <NA>  Não se aplica
3894      card  <NA>  Não informado
3895      card  <NA>  Não informado
3896      card  <NA>  Não informado
3897      card  <NA>  Não informado

In [49]:
resumo_pagamento = df.groupby("cash_type").agg(
    qtd_vendas=("cash_type", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index()

resumo_pagamento["faturamento_total"] = resumo_pagamento["faturamento_total"].round(2)
resumo_pagamento["ticket_medio"] = resumo_pagamento["ticket_medio"].round(2)

resumo_pagamento.sort_values(by="faturamento_total", ascending=False)

  cash_type  qtd_vendas  faturamento_total  ticket_medio
0      card        3729          117114.58         31.41
1      cash         169            5207.00         30.81

In [50]:
df.duplicated().sum()

np.int64(2)

In [51]:
df.isnull().sum()

date                       0
datetime                   0
cash_type                  0
card                     351
money                      0
coffee_name                0
ano                        0
mes                        0
dia                        0
hora                       0
dia_semana                 0
coffee_name_clean          0
coffee_name_formatado      0
periodo_dia                0
card_status                0
dtype: int64

In [52]:
df[df.duplicated(keep=False)]

,date,datetime,cash_type,card,money,coffee_name,ano,mes,dia,hora,dia_semana,coffee_name_clean,coffee_name_formatado,periodo_dia,card_status
3746,2025-02-26,2025-02-26 09:41:12,cash,<NA>,25.0,Americano with milk,2025,2,26,9,Wednesday,americano with milk,Americano With Milk,Manhã,Não se aplica
3747,2025-02-26,2025-02-26 09:41:12,cash,<NA>,25.0,Americano with milk,2025,2,26,9,Wednesday,americano with milk,Americano With Milk,Manhã,Não se aplica
3891,2025-03-23,2025-03-23 10:25:48,cash,<NA>,25.0,Americano with milk,2025,3,23,10,Sunday,americano with milk,Americano With Milk,Manhã,Não se aplica
3892,2025-03-23,2025-03-23 10:25:48,cash,<NA>,25.0,Americano with milk,2025,3,23,10,Sunday,americano with milk,Americano With Milk,Manhã,Não se aplica

In [53]:
df = df.drop_duplicates()

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.shape

(3896, 15)

In [56]:
df = df.reset_index(drop=True)

In [57]:
df.shape
df.duplicated().sum()

np.int64(0)

In [61]:
resumo_cafe
resumo_hora
resumo_dia_semana
resumo_periodo
resumo_pagamento

  cash_type  qtd_vendas  faturamento_total  ticket_medio
0      card        3729          117114.58         31.41
1      cash         169            5207.00         30.81

In [59]:
df.shape
df.duplicated().sum()

np.int64(0)

In [62]:
resumo_pagamento = df.groupby("cash_type").agg(
    qtd_vendas=("cash_type", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index()

resumo_pagamento["faturamento_total"] = resumo_pagamento["faturamento_total"].round(2)
resumo_pagamento["ticket_medio"] = resumo_pagamento["ticket_medio"].round(2)

resumo_pagamento.sort_values(by="faturamento_total", ascending=False)

  cash_type  qtd_vendas  faturamento_total  ticket_medio
0      card        3729          117114.58         31.41
1      cash         167            5157.00         30.88

In [63]:
resumo_cafe
resumo_hora
resumo_dia_semana
resumo_periodo

,periodo_dia,qtd_vendas,faturamento_total,ticket_medio,horas_ativas,vendas_media_por_hora,faturamento_medio_por_hora
0,Manhã,1287,39106.20,30.39,6,214.50,6517.70
1,Almoço/Início da tarde,757,23345.18,30.84,3,252.33,7781.73
2,Tarde,841,26763.62,31.82,3,280.33,8921.21
3,Noite,1013,33106.58,32.68,6,168.83,5517.76

In [64]:
resumo_cafe = df.groupby("coffee_name_formatado").agg(
    qtd_vendas=("coffee_name_formatado", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index().sort_values(by="faturamento_total", ascending=False)

resumo_cafe["faturamento_total"] = resumo_cafe["faturamento_total"].round(2)
resumo_cafe["ticket_medio"] = resumo_cafe["ticket_medio"].round(2)

In [65]:
resumo_hora = df.groupby("hora").agg(
    qtd_vendas=("hora", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index().sort_values(by="hora")

resumo_hora["faturamento_total"] = resumo_hora["faturamento_total"].round(2)
resumo_hora["ticket_medio"] = resumo_hora["ticket_medio"].round(2)

In [66]:
resumo_dia_semana = df.groupby("dia_semana").agg(
    qtd_vendas=("dia_semana", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean")
).reset_index()

resumo_dia_semana["faturamento_total"] = resumo_dia_semana["faturamento_total"].round(2)
resumo_dia_semana["ticket_medio"] = resumo_dia_semana["ticket_medio"].round(2)

In [67]:
resumo_periodo = df.groupby("periodo_dia").agg(
    qtd_vendas=("periodo_dia", "count"),
    faturamento_total=("money", "sum"),
    ticket_medio=("money", "mean"),
    horas_ativas=("hora", "nunique")
).reset_index()

resumo_periodo["faturamento_total"] = resumo_periodo["faturamento_total"].round(2)
resumo_periodo["ticket_medio"] = resumo_periodo["ticket_medio"].round(2)

resumo_periodo["vendas_media_por_hora"] = (
    resumo_periodo["qtd_vendas"] / resumo_periodo["horas_ativas"]
).round(2)

resumo_periodo["faturamento_medio_por_hora"] = (
    resumo_periodo["faturamento_total"] / resumo_periodo["horas_ativas"]
).round(2)

resumo_periodo.sort_values(by="faturamento_medio_por_hora", ascending=False)

,periodo_dia,qtd_vendas,faturamento_total,ticket_medio,horas_ativas,vendas_media_por_hora,faturamento_medio_por_hora
2,Tarde,841,26763.62,31.82,3,280.33,8921.21
1,Almoço/Início da tarde,757,23345.18,30.84,3,252.33,7781.73
0,Manhã,1285,39056.20,30.39,6,214.17,6509.37
3,Noite,1013,33106.58,32.68,6,168.83,5517.76

In [68]:
df.to_csv("coffee_sales_tratado.csv", index=False)

resumo_cafe.to_csv("resumo_cafe.csv", index=False)
resumo_hora.to_csv("resumo_hora.csv", index=False)
resumo_dia_semana.to_csv("resumo_dia_semana.csv", index=False)
resumo_periodo.to_csv("resumo_periodo.csv", index=False)
resumo_pagamento.to_csv("resumo_pagamento.csv", index=False)